# Generated by Django 6.1 on 2026-08-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cateogory',
            new_name='category',
        ),
    ]
